services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
    container_name: temp-sensor-api
    ports:
      - "${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      DEFAULT_HOT_THRESHOLD: ${DEFAULT_HOT_THRESHOLD}
      DEFAULT_COLD_THRESHOLD: ${DEFAULT_COLD_THRESHOLD}
    volumes:
      - ./src:/app/src:ro
      # - /app/src/infrastructure/database/generated
      - ./package.json:/app/package.json
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:18-alpine
    container_name: temp-sensor-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

# For futur use in CI/CD pipelines
# test:
#   build:
#     context: .
#     dockerfile: docker/Dockerfile
#     target: test
#   container_name: temp-sensor-test
#   environment:
#     NODE_ENV: test
#     DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
#     DEFAULT_HOT_THRESHOLD: 35
#     DEFAULT_COLD_THRESHOLD: 22
#   depends_on:
#     db:
#       condition: service_healthy
#   networks:
#     - app-network
#   profiles:
#     - test

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
