export const CLOCK_PORT = Symbol('CLOCK_PORT');
export const ID_GENERATOR_PORT = Symbol('ID_GENERATOR_PORT');
export const TEMPERATURE_HISTORY_REPOSITORY = Symbol(
  'TEMPERATURE_HISTORY_REPOSITORY',
);
export const TEMPERATURE_SENSOR_PORT = Symbol('TEMPERATURE_SENSOR_PORT');
export const THRESHOLDS_REPOSITORY = Symbol('THRESHOLDS_REPOSITORY');
